{% set name = "pynteny" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/Robaina/pynteny/archive/v{{ version }}.tar.gz

build:
  number: 2
  entry_points:
    - pynteny = pynteny.cli:main
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - poetry
    - pip
  run:
    - python
    - hmmer
    - prodigal
    - pyfastx
    - biopython
    - numpy
    - pandas
    - seqkit
    - psutil
    - requests
    - tqdm

test:
  imports:
    - pynteny
  commands:
    - pynteny --help

about:
  home: "http://github.com/robaina/Pynteny"
  license: Apache-2.0 license
  summary: "Multiple HMM - search via synteny structures in Python"
  doc_url: "https://robaina.github.io/Pynteny/"

extra:
  recipe-maintainers:
    - Robaina
  identifiers:
    - DOI:10.5281/zenodo.7082448
